{% set name = "classixclustering" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}



source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d064395b3192019aebbb7fed9e69f715b55711eaf8a942154393b10847da2d61


build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
    
requirements:
  build:
    - python >=3.6
    - pip
    - numpy 
    - cython

  run:
    - python >=3.6
    - pandas
    - requests
    - numpy
    - scipy ==1.7.2
    - matplotlib-base

test:
  imports:
    - classix


about:
  home: https://github.com/nla-group/classix
  summary: 'CLASSIX is a fast and explainable clustering algorithm based on sorting.'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/nla-group/classix

extra:
  recipe-maintainers:
    - chenxinye
    - guettel
