{% set name = "classixclustering" %}
{% set version_info = load_json("https://pypi.org/pypi/{}/json".format(name)) %}
{% set version = version_info["info"]["version"] %}
{% set url = version_info["urls"][0]["url"] %}
{% set sha256 = version_info["urls"][0]["digests"]["sha256"] %}
{% set python_min = ">=3.12,<3.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cython
  host:
    - python {{ python_min }}
    - pip
    - numpy >=1.22
    - cython
  run:
    - python {{ python_min }}
    - pandas >=2.1
    - requests
    - numpy >=1.22
    - scipy >=1.11,<2.0
    - matplotlib-base >=3.8
    - scikit-learn >=1.2,<2.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - classix
  commands:
    - python -c "import classix; print('classix imported successfully')"

about:
  home: https://github.com/nla-group/classix
  summary: CLASSIX is a fast and explainable clustering algorithm based on sorting.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/nla-group/classix

extra:
  recipe-maintainers:
    - chenxinye
    - guettel
