{% set python_min = ">=3.12,<3.13" %}
{% set python_min = ">=3.12,<3.13" %}
{% set name = "classixclustering" %}
{% set version = "1.3.8" %}
{% set python_min = ">=3.12,<3.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 80e7dade1b90294091c8af130d1ae7c38a36f2b5e7d5da348e3ff21b0b8b494d

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python {{ python_min }}
    - pip
    - numpy 2.3.*
    - cython
  run:
    - python {{ python_min }}
    - pandas >=2.1
    - requests
    - numpy 2.3.*
    - scipy >=1.11,<2.0
    - matplotlib-base >=3.8
    - scikit-learn >=1.2,<2.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - classix
  commands:
    - python -c "import classix; print('classix imported successfully')"

about:
  home: https://github.com/nla-group/classix
  summary: CLASSIX is a fast and explainable clustering algorithm based on sorting.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/nla-group/classix

extra:
  recipe-maintainers:
    - guettel
    - chenxinye
