{% set python_min = ">=3.12,<3.13" %}
{% set python_min = ">=3.12,<3.13" %}
{% set name = "classixclustering" %}
{% set version = "1.4.3" %}
{% set python_min = ">=3.12,<3.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0ed4dec490e2ff1ed631ac21ef52e3a2634a1cc623f1e4d10750583f25aa3509

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cython
  host:
    - python {{ python_min }}
    - pip
    - numpy 2.3.*
    - cython
  run:
    - python {{ python_min }}
    - pandas >=2.1
    - requests
    - numpy 2.3.*
    - scipy >=1.11,<2.0
    - matplotlib-base >=3.8
    - scikit-learn >=1.2,<2.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - classix
  commands:
    - python -c "import classix; print('classix imported successfully')"

about:
  home: https://github.com/nla-group/classix
  summary: CLASSIX is a fast and explainable clustering algorithm based on sorting.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/nla-group/classix

extra:
  recipe-maintainers:
    - guettel
    - chenxinye
