{% set name = "classixclustering" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d0f72deccb40ca9eb14905bb1a0f41787a824446eebac5a67a7ae59ec4c65342

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.6
    - pip
    - numpy
    - cython

  run:
    - python >=3.6
    - pandas
    - requests
    - {{ pin_compatible('numpy') }}
    - scipy ==1.7.2
    - matplotlib-base

test:
  imports:
    - classix

about:
  home: https://github.com/nla-group/classix
  summary: CLASSIX is a fast and explainable clustering algorithm based on sorting.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/nla-group/classix

extra:
  recipe-maintainers:
    - guettel
    - chenxinye
